name: sign_language_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  google_sign_in: ^7.1.1
  sqflite: ^2.4.1
  shimmer_animation: ^2.2.2
  appwrite: ^17.0.2
  agora_rtc_engine: ^6.5.2
  permission_handler: ^12.0.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_core_platform_interface: ^6.0.0
  firebase_storage: ^13.0.0
  cached_network_image: ^3.3.1
  intl_phone_number_input: ^0.7.4
  shared_preferences: ^2.3.2
  image_picker: ^1.0.4
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  cloud_firestore: ^6.0.1
  uuid: ^4.5.1
  firebase_app_check: ^0.4.1+1
  pay_with_paystack: ^1.0.14
  flutter_dotenv: ^5.1.0
  flutter_webrtc: ^0.12.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env

  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Medium.ttf
        - asset: fonts/WorkSans-SemiBold.ttf
        - asset: fonts/WorkSans-Bold.ttf
        - asset: fonts/WorkSans-ExtraBold.ttf
